import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/layout/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <div className="min-h-screen bg-zinc-950 bg-[radial-gradient(circle_at_top,_rgba(16,185,129,0.08),_rgba(9,9,11,1)_52%)] text-zinc-100">
          <Sidebar />
          <main className="min-h-screen overflow-auto md:ml-[220px]">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
