"""Boot-time content seeding for the Endgame Trainer.

WHY THIS EXISTS
===============
The endgame library is content, not schema. Migrations create
endgame_topics / endgame_positions / endgame_common_mistakes empty, and the
rows have always come from standalone, hand-run seeders:

  * src/seed_endgames.py                 -- the curated teaching set (Lucena
                                            Position + 3 mistake explanations)
  * scripts/import_sourced_endgames.py   -- 22,378 tablebase-verified sourced
                                            positions across 111 material
                                            topics, imported from a survivor
                                            run against local Syzygy

Neither was wired into deploy, and both were only ever run against
localhost. The 2026-09-21 production deploy therefore booted with an empty
library and the trainer answered "no endgame drill positions in rating
range 1000-1300". This module makes the app self-seed at boot so a fresh
database can never boot empty again.

WHAT RUNS WHEN
==============
  * Curated content: EVERY boot. It is a couple dozen tiny idempotent
    statements, and re-running is deliberate: the seeder's mistake inserts
    are ON CONFLICT DO UPDATE, so edited explanation prose ships with the
    deploy (the seeder is the content source of truth for those rows; see
    src/seed_endgames.py).
  * Sourced content: ONLY when the sourced pool is empty. The importer
    re-probes 7,797 drill starts against the image's local Syzygy
    (~60-90s CPU) and inserts 22k rows; it must not sit in the normal boot
    path. Once seeded, this costs one EXISTS query per boot.

The import input is the committed, gzipped deploy artifact
(data/seed/endgame_sourced_seed.jsonl.gz, 2.6 MB, generated by
`import_sourced_endgames.py --export-seed`). It must be committed because
CI builds the image from a clean checkout and the raw
data/processed/endgame_candidates/ run is gitignored. The working
survivors.jsonl is used as a fallback for local runs.

BOOT POLICY
===========
main.py starts this on a daemon thread AFTER migrations, so a first boot
can import in the background while the API serves. That trades a short
window of "empty" on a brand-new database for a boot that never blocks on
CPU-heavy seeding. A Postgres advisory lock elects one seeding replica;
concurrent replicas skip instead of double-probing. Failures are logged
loudly but never take the app down -- an empty library is the bug being
fixed, a dead API would be worse.

Subprocesses (rather than in-process imports) are used for two reasons:
the seeders are the documented, independently runnable entry points, and
the importer's chess probing is CPU-bound -- in a thread it would fight
the asyncio loop for the GIL, while a child process gets its own.

MANUAL FALLBACK
===============
If ENDGAME_AUTO_SEED is off (or an artifact is missing), run the same
commands by hand against the target database:

    python src/seed_endgames.py
    python scripts/import_sourced_endgames.py --apply
    python scripts/import_sourced_endgames.py --backfill-source-ids
"""
import logging
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Callable, List, Optional, Tuple

import psycopg2

log = logging.getLogger(__name__)

ROOT_DIR = Path(__file__).resolve().parents[2]
CURATED_SCRIPT = ROOT_DIR / "src" / "seed_endgames.py"
SOURCED_SCRIPT = ROOT_DIR / "scripts" / "import_sourced_endgames.py"

# Committed first (what the deployed image has); the local working run as a
# fallback so a dev machine seeds from the freshest sourcing output.
COMMITTED_SOURCED_SEED = ROOT_DIR / "data" / "seed" / "endgame_sourced_seed.jsonl.gz"
WORKING_SURVIVORS = (
    ROOT_DIR / "data" / "processed" / "endgame_candidates" / "survivors.jsonl"
)
TABLEBASE_DIR = Path(
    os.getenv("SYZYGY_TABLEBASE_DIR", str(ROOT_DIR / "data" / "syzygy" / "regular"))
)

# Arbitrary but stable namespace for pg_try_advisory_lock across replicas.
SEED_LOCK_KEY = 7_720_230_921

CURATED_TIMEOUT_S = 180
SOURCED_TIMEOUT_S = 1200

# (label, argv, timeout) -> succeeded
Runner = Callable[[str, List[str], int], bool]


def auto_seed_enabled() -> bool:
    """ENDGAME_AUTO_SEED defaults on; off/0/no/false disables boot seeding."""
    raw = os.getenv("ENDGAME_AUTO_SEED", "on").strip().lower()
    return raw not in {"0", "false", "no", "off"}


def _db_config() -> dict:
    """Same resolution order as the seeders: discrete DB_* vars first, the
    app's DATABASE_URL as fallback (container env sets only the latter)."""
    config = {
        "dbname": os.getenv("DB_NAME"),
        "user": os.getenv("DB_USER"),
        "password": os.getenv("DB_PASSWORD"),
        "host": os.getenv("DB_HOST", "localhost"),
        "port": int(os.getenv("DB_PORT", 5432)),
    }
    if not all([config["dbname"], config["user"], config["password"]]):
        dsn = os.getenv("DATABASE_URL")
        return {"dsn": dsn} if dsn and "://" in dsn else {}
    return config


def _connect():
    config = _db_config()
    if not config:
        raise RuntimeError("no usable DB config (DB_NAME/DB_USER/DB_PASSWORD or DATABASE_URL)")
    return psycopg2.connect(**config)


def sourced_pool_empty(conn) -> bool:
    """True when no sourced drill row exists (the import never completed).

    The check keys on source_puzzle_id because that is the import's LAST
    step: if --backfill-source-ids failed, rows exist but the column is
    NULL, and re-running the (idempotent) import + backfill is exactly the
    repair this triggers.
    """
    with conn.cursor() as cur:
        cur.execute(
            "SELECT NOT EXISTS ("
            "  SELECT 1 FROM endgame_positions WHERE source_puzzle_id IS NOT NULL"
            ")"
        )
        return bool(cur.fetchone()[0])


def _sourced_input_path() -> Optional[Path]:
    for candidate in (COMMITTED_SOURCED_SEED, WORKING_SURVIVORS):
        if candidate.is_file():
            return candidate
    return None


def _sourced_artifacts_ready() -> Tuple[bool, Optional[Path]]:
    """The import needs an input file AND the local Syzygy set (the <=5-man
    re-probe). Both are baked into the deploy image: the committed seed via
    git, the tablebases via Dockerfile.base's pre-warm."""
    input_path = _sourced_input_path()
    return (input_path is not None and TABLEBASE_DIR.is_dir(), input_path)


def _run_script(label: str, args: List[str], timeout_s: int) -> bool:
    """Run one seeder subprocess, log a bounded output tail, never raise.

    stderr is merged into stdout so the seeders' logging output (they log to
    stderr by default) appears in the boot log on success too, not only in
    the failure path.
    """
    log.info("endgame seeding [%s]: %s", label, " ".join(args))
    try:
        completed = subprocess.run(
            [sys.executable, *args],
            cwd=ROOT_DIR,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            timeout=timeout_s,
        )
    except Exception as exc:  # noqa: BLE001 - seeding must never break boot
        log.exception("endgame seeding [%s] could not run: %s", label, exc)
        return False

    tail = (completed.stdout or "").strip().splitlines()[-10:]
    if completed.returncode != 0:
        log.error(
            "endgame seeding [%s] failed (exit %s); output tail: %s",
            label,
            completed.returncode,
            " | ".join(tail),
        )
        return False
    for line in tail:
        log.info("endgame seeding [%s]: %s", label, line)
    return True


def seed_missing_content(conn, *, runner: Runner = _run_script) -> None:
    """Ensure curated content, then import sourced rows iff the pool is empty."""
    runner("curated", [str(CURATED_SCRIPT)], CURATED_TIMEOUT_S)

    if not sourced_pool_empty(conn):
        log.info("endgame seeding: sourced pool present; import not needed")
        return

    ready, input_path = _sourced_artifacts_ready()
    if not ready:
        log.error(
            "endgame seeding: sourced pool is EMPTY but artifacts are missing "
            "(input=%s exists=%s, tablebase=%s exists=%s); run "
            "scripts/import_sourced_endgames.py --apply manually",
            _sourced_input_path() or COMMITTED_SOURCED_SEED,
            _sourced_input_path() is not None,
            TABLEBASE_DIR,
            TABLEBASE_DIR.is_dir(),
        )
        return

    report_dir = Path(tempfile.gettempdir()) / "endgame_seed"
    if not runner(
        "sourced-import",
        [
            str(SOURCED_SCRIPT),
            "--apply",
            "--survivors",
            str(input_path),
            "--out-dir",
            str(report_dir),
        ],
        SOURCED_TIMEOUT_S,
    ):
        # The import writes source_puzzle_id only via the backfill step, so
        # a failed import must not be followed by it.
        return
    runner(
        "sourced-backfill",
        [str(SOURCED_SCRIPT), "--backfill-source-ids", "--survivors", str(input_path)],
        CURATED_TIMEOUT_S,
    )


def _try_lock(conn) -> bool:
    with conn.cursor() as cur:
        cur.execute("SELECT pg_try_advisory_lock(%s)", (SEED_LOCK_KEY,))
        return bool(cur.fetchone()[0])


def _unlock(conn) -> None:
    with conn.cursor() as cur:
        cur.execute("SELECT pg_advisory_unlock(%s)", (SEED_LOCK_KEY,))


def ensure_endgame_content() -> None:
    """Entry point for main.py's boot thread. Never raises."""
    if not auto_seed_enabled():
        log.info("endgame seeding: disabled via ENDGAME_AUTO_SEED")
        return

    try:
        conn = _connect()
    except Exception as exc:  # noqa: BLE001
        log.exception("endgame seeding: no database connection: %s", exc)
        return

    try:
        try:
            locked = _try_lock(conn)
        except Exception as exc:  # noqa: BLE001
            log.exception("endgame seeding: cannot take the seed lock: %s", exc)
            return
        if not locked:
            log.info("endgame seeding: another replica holds the seed lock")
            return
        try:
            seed_missing_content(conn)
        except Exception as exc:  # noqa: BLE001
            log.exception("endgame seeding: unexpected failure: %s", exc)
        finally:
            try:
                _unlock(conn)
            except Exception:  # noqa: BLE001
                log.warning("endgame seeding: could not release the seed lock")
    finally:
        conn.close()
