#!/usr/bin/env python
"""
Build the static mini-board previews used by the /puzzles theme picker.

WHAT THIS PRODUCES
==================
frontend/src/lib/puzzleThemePreviews.ts -- one representative position per
Lichess puzzle theme category (the first key in each category in
frontend/src/lib/themes.ts), rendered in the theme picker as a miniature
walnut chessboard:

  * fen         the position AFTER the opponent's setup move, i.e. exactly
                the position the solver sees when the puzzle starts.
  * from / to   UCI squares of the key move (the solution's first move), drawn
                as a gold arrow on the mini board so the motif is legible at a
                glance.
  * orientation the side to move, so the preview matches the solver's view.

WHY A STATIC FILE
=================
The picker renders one preview per category. Keeping these five sampled
positions in the bundle avoids runtime requests and lets the mini boards
hydrate lazily. Re-run this script to refresh.

SAMPLING
========
Candidates are drawn from the puzzles table (DATABASE_URL, or the local dev
DSN). Selection is deterministic -- ordered by md5(id) -- so re-running is
stable unless the table changes. Mid-rated puzzles are preferred, and mate
themes prefer short solution lines so the pattern stays readable at 48px.
Rows are tried in order until one yields a valid setup move via python-chess.

USAGE
=====
    source venv/bin/activate
    python scripts/build_puzzle_theme_previews.py

    # custom output / connection
    python scripts/build_puzzle_theme_previews.py --out /tmp/previews.ts \
        --database-url postgresql://user:pass@host:5432/praxis
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

import chess
import psycopg2

ROOT = Path(__file__).resolve().parents[1]
THEMES_TS = ROOT / "frontend" / "src" / "lib" / "themes.ts"
DEFAULT_OUT = ROOT / "frontend" / "src" / "lib" / "puzzleThemePreviews.ts"
DEFAULT_DSN = "postgresql://praxis_user:praxis123@localhost:5432/praxis"

THEME_GROUP_RE = re.compile(r"themes:\s*\[(.*?)\]", re.DOTALL)
KEY_RE = re.compile(r"key:\s*'([^']+)'")
CANDIDATES_PER_TIER = 10


def theme_keys() -> list[str]:
    """Read the first theme in each category from themes.ts."""
    groups = THEME_GROUP_RE.findall(THEMES_TS.read_text())
    return [match.group(1) for group in groups if (match := KEY_RE.search(group))]


def prefers_short_lines(theme: str) -> bool:
    """Mate patterns read best as short, forced lines."""
    return "mate" in theme.lower()


def candidate_queries(theme: str) -> list[str]:
    """Progressively looser filters; each returns candidate rows to try."""
    length = "array_length(string_to_array(moves, ' '), 1)"
    if prefers_short_lines(theme):
        order = f"{length} ASC, md5(id)"
    else:
        order = "md5(id)"

    select = (
        "SELECT id, fen, moves FROM puzzles "
        "WHERE themes @> ARRAY[%s]::text[] "
        "AND fen <> '' "
        f"AND {length} >= 2 "
    )
    return [
        select + f"AND rating BETWEEN 1400 AND 1900 AND {length} <= 8 "
        f"ORDER BY {order} LIMIT {CANDIDATES_PER_TIER}",
        select + f"AND rating BETWEEN 1000 AND 2200 ORDER BY {order} "
        f"LIMIT {CANDIDATES_PER_TIER}",
        select + f"ORDER BY {order} LIMIT {CANDIDATES_PER_TIER}",
    ]


def build_preview(fen: str, moves: str) -> dict[str, str] | None:
    """Apply the setup move and return the solver-view position + key move."""
    tokens = moves.split()
    if len(tokens) < 2:
        return None

    try:
        board = chess.Board(fen)
        board.push_uci(tokens[0])
        board.push_uci(tokens[1])  # validate the arrow move exists
        board.pop()
    except ValueError:
        return None

    return {
        "fen": board.fen(),
        "from": tokens[1][:2],
        "to": tokens[1][2:4],
        "orientation": "white" if board.turn == chess.WHITE else "black",
    }


def sample_theme(cur, theme: str) -> dict[str, str] | None:
    for query in candidate_queries(theme):
        cur.execute(query, (theme,))
        for _puzzle_id, fen, moves in cur.fetchall():
            preview = build_preview(fen, moves)
            if preview is not None:
                return preview
    return None


def render_ts(previews: dict[str, dict[str, str]]) -> str:
    lines = [
        "// Generated by scripts/build_puzzle_theme_previews.py -- do not edit",
        "// by hand. Re-run the script to refresh the sampled positions.",
        "",
        "export type PuzzleThemePreview = {",
        "  /** Solver's view: position after the opponent's setup move. */",
        "  fen: string;",
        "  /** UCI squares of the key move, drawn as a gold arrow. */",
        "  from: string;",
        "  to: string;",
        "  orientation: 'white' | 'black';",
        "};",
        "",
        "export const PUZZLE_THEME_PREVIEWS: Record<string, PuzzleThemePreview> = {",
    ]
    for key, preview in previews.items():
        lines.append(
            f"  {key}: {{ fen: '{preview['fen']}', from: '{preview['from']}', "
            f"to: '{preview['to']}', orientation: '{preview['orientation']}' }},"
        )
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--database-url", default=None, help="Postgres DSN")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="TS output path")
    args = parser.parse_args()

    dsn = args.database_url or os.environ.get("DATABASE_URL") or DEFAULT_DSN
    keys = theme_keys()
    if not keys:
        print(f"No theme keys parsed from {THEMES_TS}", file=sys.stderr)
        return 1

    conn = psycopg2.connect(dsn)
    cur = conn.cursor()

    previews: dict[str, dict[str, str]] = {}
    missing: list[str] = []
    for key in keys:
        preview = sample_theme(cur, key)
        if preview is None:
            missing.append(key)
            continue
        previews[key] = preview
        print(f"{key:20s} {preview['from']}->{preview['to']}  {preview['orientation']}")

    if missing:
        for key in missing:
            print(f"No sample for: {key}", file=sys.stderr)
        return 1

    conn.close()

    args.out.write_text(render_ts(previews))
    print(f"\nWrote {len(previews)} previews to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
