// Generated by scripts/build_puzzle_theme_previews.py -- do not edit
// by hand. Re-run the script to refresh the sampled positions.

export type PuzzleThemePreview = {
  /** Solver's view: position after the opponent's setup move. */
  fen: string;
  /** UCI squares of the key move, drawn as a gold arrow. */
  from: string;
  to: string;
  orientation: 'white' | 'black';
};

export const PUZZLE_THEME_PREVIEWS: Record<string, PuzzleThemePreview> = {
  advancedPawn: { fen: '8/1p1k4/3pRp2/2bP3p/2P2BpP/1P4P1/2K5/5r2 b - - 3 42', from: 'f1', to: 'f4', orientation: 'black' },
  attraction: { fen: 'r5k1/1pb2ppp/p1p5/2P5/1P2B3/PQ2PRqr/1B4P1/3R2K1 b - - 0 24', from: 'h3', to: 'h1', orientation: 'black' },
  mate: { fen: '6N1/1p2Q1b1/p1n3p1/7k/2P5/1P5P/P2q2P1/5K2 w - - 10 43', from: 'g2', to: 'g4', orientation: 'white' },
  anastasiaMate: { fen: 'r6r/pp2Nppk/3B1b2/3P3p/8/2q2Q1P/P5P1/R6K w - - 2 24', from: 'f3', to: 'h5', orientation: 'white' },
  castling: { fen: '3rkbnr/p1p2ppp/b1P1p3/8/P1p5/4PN2/qBQ1BPPP/1N2K2R w Kk - 0 14', from: 'b1', to: 'c3', orientation: 'white' },
};
